project_id = "zoahzxfjefjmkxylbfxf"

[functions.ingest-metrics]
verify_jwt = false

[functions.ingest-campaigns]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

# Public endpoints used by Diagnóstico Google Ads UI
[functions.google-ads-ping]
verify_jwt = false

[functions.google-ads-sync-accounts]
verify_jwt = false

[functions.google-ads-accounts]
verify_jwt = false

[functions.google-ads-ingest]
verify_jwt = false

[functions.google-ads-diag]
verify_jwt = false

[functions.google-ads-connect]
verify_jwt = false

[functions.google-ads-sync]
verify_jwt = false

[functions.google-ads-ingest-daily]
verify_jwt = false

[functions.resolve-mcc]
verify_jwt = false

# New diagnostic endpoints - protected by x-api-key
[functions.google-ads-diag-context]
verify_jwt = false

[functions.google-ads-diag-hierarchy]
verify_jwt = false

[functions.google-ads-diag-ping-ingest]
verify_jwt = false

# Reporting endpoints - protected by x-api-key
[functions.reports-last30]
verify_jwt = false

[functions.reports-daily-campaign]
verify_jwt = false