// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoahzxfjefjmkxylbfxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYWh6eGZqZWZqbWt4eWxiZnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzkzMzEsImV4cCI6MjA3MzcxNTMzMX0.tjxHTtuqbh6zWPmZif8T5oL3cWroYMLFt5BCYc0GQ2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});